SistemaSeguros/Controllers/ClientesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using SistemaSeguros;

namespace SistemaSeguros.Controllers
{
    public class ClientesController : Controller
    {
        private SistemaSegurosEntities db = new SistemaSegurosEntities();

        // GET: Clientes
        public async Task<ActionResult> Index()
        {
            return View(await db.Cliente.ToListAsync());
        }

        // GET: Clientes/Details/5
        public async Task<ActionResult> Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Cliente cliente = await db.Cliente.FindAsync(id);
            if (cliente == null)
            {
                return HttpNotFound();
            }
            return View(cliente);
        }

        // GET: Clientes/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Clientes/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "Identificacion,Nombre,Apellidos,FechaNacimiento,Direccion")] Cliente cliente)
        {
            if (ModelState.IsValid)
            {
                db.Cliente.Add(cliente);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            return View(cliente);
        }

        // GET: Clientes/Edit/5
        public async Task<ActionResult> Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Cliente cliente = await db.Cliente.FindAsync(id);
            if (cliente == null)
            {
                return HttpNotFound();
            }
            return View(cliente);
        }

        // POST: Clientes/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "Identificacion,Nombre,Apellidos,FechaNacimiento,Direccion")] Cliente cliente)
        {
            if (ModelState.IsValid)
            {
                db.Entry(cliente).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(cliente);
        }

        // GET: Clientes/Delete/5
        public async Task<ActionResult> Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Cliente cliente = await db.Cliente.FindAsync(id);
            if (cliente == null)
            {
                return HttpNotFound();
            }
            return View(cliente);
        }

        // POST: Clientes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(string id)
        {
            Cliente cliente = await db.Cliente.FindAsync(id);
            db.Cliente.Remove(cliente);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

SistemaSeguros/Controllers/PolizaPorClientesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using SistemaSeguros;

namespace SistemaSeguros.Controllers
{
    public class PolizaPorClientesController : Controller
    {
        private SistemaSegurosEntities db = new SistemaSegurosEntities();

        // GET: PolizaPorClientes
        public async Task<ActionResult> Index(string idCliente, string nombreCompleto)
        {
            ViewBag.idCliente = idCliente;
            ViewBag.NombreCompleto = nombreCompleto;
            var polizaPorCliente = (!string.IsNullOrEmpty(idCliente)) ? db.PolizaPorCliente.Include(p => p.Cliente).Include(p => p.Poliza).Where(c => c.FK_IDCliente == idCliente) : db.PolizaPorCliente.Include(p => p.Cliente).Include(p => p.Poliza);
            return View(await polizaPorCliente.ToListAsync());
        }

        // GET: PolizaPorClientes/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            PolizaPorCliente polizaPorCliente = await db.PolizaPorCliente.FindAsync(id);
            if (polizaPorCliente == null)
            {
                return HttpNotFound();
            }
            return View(polizaPorCliente);
        }

        // GET: PolizaPorClientes/Create
        public ActionResult Create(string idCliente, string nombreCompleto, string tipo)
        {
            ViewBag.idCliente = idCliente;
            ViewBag.nombreCompleto = nombreCompleto;
            ViewBag.tipo = tipo;
            ViewBag.FK_IDCliente = new SelectList(db.Cliente.Select(x => new { x.Identificacion, Nombre = (x.Identificacion+" - "+x.Nombre+" "+x.Apellidos) }), "Identificacion", "Nombre", idCliente);
            ViewBag.FK_IDEstado = new SelectList(db.EstadoPoliza, "Codigo", "Descripcion");
            ViewBag.FK_IDPoliza = new SelectList(db.Poliza, "ID_Poliza", "Nombre");
            return View();
        }

        // POST: PolizaPorClientes/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(string idCliente, string nombreCompleto)
        {
            return RedirectToAction("Index", new { idCliente = idCliente, nombreCompleto = nombreCompleto });

            //if (ModelState.IsValid)
            //{
            //    db.PolizaPorCliente.Add(polizaPorCliente);
            //    await db.SaveChangesAsync();
                
            //}

            //ViewBag.FK_IDCliente = new SelectList(db.Cliente, "Identificacion", "Nombre", polizaPorCliente.FK_IDCliente);
            //ViewBag.FK_IDEstado = new SelectList(db.EstadoPoliza, "Codigo", "Descripcion", polizaPorCliente.FK_IDEstado);
            //ViewBag.FK_IDPoliza = new SelectList(db.Poliza, "ID_Poliza", "Nombre", polizaPorCliente.FK_IDPoliza);
            //return View(polizaPorCliente);
        }

        // GET: PolizaPorClientes/Edit/5
        public async Task<ActionResult> Edit(int? id, string idCliente, string nombreCompleto, string tipo)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ViewBag.idCliente = idCliente;
            ViewBag.nombreCompleto = nombreCompleto;
            ViewBag.tipo = tipo;
            PolizaPorCliente polizaPorCliente = await db.PolizaPorCliente.FindAsync(id);
            if (polizaPorCliente == null)
            {
                return HttpNotFound();
            }
            ViewBag.FK_IDCliente = new SelectList(db.Cliente.Select(x => new { x.Identificacion, Nombre = (x.Identificacion + " - " + x.Nombre + " " + x.Apellidos) }), "Identificacion", "Nombre",polizaPorCliente.FK_IDCliente);
            ViewBag.FK_IDEstado = new SelectList(db.EstadoPoliza, "Codigo", "Descripcion", polizaPorCliente.FK_IDEstado);
            ViewBag.FK_IDPoliza = new SelectList(db.Poliza, "ID_Poliza", "Nombre", polizaPorCliente.FK_IDPoliza);
            return View(polizaPorCliente);
        }

        // POST: PolizaPorClientes/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "ID_PolizaCliente,FK_IDCliente,FK_IDPoliza,InicioVigenciaPoliza,PrecioPolizaAdquirida,MesesCobertura,FK_IDEstado")] PolizaPorCliente polizaPorCliente)
        {
            if (ModelState.IsValid)
            {
                db.Entry(polizaPorCliente).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            ViewBag.FK_IDCliente = new SelectList(db.Cliente, "Identificacion", "Nombre", polizaPorCliente.FK_IDCliente);
            ViewBag.FK_IDEstado = new SelectList(db.EstadoPoliza, "Codigo", "Descripcion", polizaPorCliente.FK_IDEstado);
            ViewBag.FK_IDPoliza = new SelectList(db.Poliza, "ID_Poliza", "Nombre", polizaPorCliente.FK_IDPoliza);
            return View(polizaPorCliente);
        }

        // GET: PolizaPorClientes/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            PolizaPorCliente polizaPorCliente = await db.PolizaPorCliente.FindAsync(id);
            if (polizaPorCliente == null)
            {
                return HttpNotFound();
            }
            return View(polizaPorCliente);
        }

        // POST: PolizaPorClientes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            PolizaPorCliente polizaPorCliente = await db.PolizaPorCliente.FindAsync(id);
            db.PolizaPorCliente.Remove(polizaPorCliente);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

SistemaSeguros/Views/Clientes/Create.cshtml
@model SistemaSeguros.Cliente

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Cliente</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Identificacion, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Identificacion, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Identificacion, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Nombre, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nombre, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nombre, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Apellidos, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Apellidos, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Apellidos, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FechaNacimiento, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FechaNacimiento, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FechaNacimiento, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Direccion, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Direccion, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Direccion, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

SistemaSeguros/Views/Clientes/Delete.cshtml
@model SistemaSeguros.Cliente

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Cliente</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nombre)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Apellidos)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Apellidos)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FechaNacimiento)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FechaNacimiento)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Direccion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Direccion)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

SistemaSeguros/Views/Clientes/Details.cshtml
@model SistemaSeguros.Cliente

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>Cliente</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nombre)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Apellidos)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Apellidos)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FechaNacimiento)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FechaNacimiento)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Direccion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Direccion)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Identificacion }) |
    @Html.ActionLink("Back to List", "Index")
</p>

SistemaSeguros/Views/Clientes/Edit.cshtml
@model SistemaSeguros.Cliente

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Cliente</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Identificacion)

        <div class="form-group">
            @Html.LabelFor(model => model.Nombre, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nombre, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nombre, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Apellidos, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Apellidos, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Apellidos, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FechaNacimiento, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FechaNacimiento, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FechaNacimiento, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Direccion, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Direccion, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Direccion, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

SistemaSeguros/Views/Clientes/Index.cshtml
@model IEnumerable<SistemaSeguros.Cliente>

@{
    ViewBag.Title = "Clientes";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

    <h2>
      @ViewBag.Title
    </h2>

<table class="table">
    <thead class="thead-dark">
        <tr>
            <th>
                Identificación
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Nombre)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Apellidos)
            </th>
            <th>
                Fecha Nacimiento
            </th>
            <th>
                Dirección
            </th>
            <th></th>
        </tr>
        </thead>

        @foreach (var item in Model)
        {
<tr>
    <td>
        @Html.DisplayFor(modelItem => item.Identificacion)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.Nombre)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.Apellidos)
    </td>
    <td>
        @Convert.ToDateTime(item.FechaNacimiento).ToString("dd/MM/yyyy")
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.Direccion)
    </td>
    <td>
        @*@Html.ActionLink("Edit", "Edit", new { id = item.Identificacion }) |
            @Html.ActionLink("Details", "Details", new { id = item.Identificacion }) |
            @Html.ActionLink("Delete", "Delete", new { id = item.Identificacion })|*@
        @Html.ActionLink("Ver Pólizas", "Index", "PolizaPorClientes", new { idCliente = item.Identificacion, nombreCompleto = item.Nombre + " " + item.Apellidos }, null)
    </td>
</tr>
        }

</table>

<script>  </script>