SistemaSeguros/Controllers/CoberturasController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using SistemaSeguros;

namespace SistemaSeguros.Controllers
{
    public class CoberturasController : Controller
    {
        private SistemaSegurosEntities db = new SistemaSegurosEntities();

        // GET: Coberturas
        public async Task<ActionResult> Index()
        {
            return View(await db.Cobertura.ToListAsync());
        }

        // GET: Coberturas/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Cobertura cobertura = await db.Cobertura.FindAsync(id);
            if (cobertura == null)
            {
                return HttpNotFound();
            }
            return View(cobertura);
        }

        // GET: Coberturas/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Coberturas/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "ID_Cobertura,Nombre,Descripcion,PrecioMensual")] Cobertura cobertura)
        {
            if (ModelState.IsValid)
            {
                db.Cobertura.Add(cobertura);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            return View(cobertura);
        }

        // GET: Coberturas/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Cobertura cobertura = await db.Cobertura.FindAsync(id);
            if (cobertura == null)
            {
                return HttpNotFound();
            }
            return View(cobertura);
        }

        // POST: Coberturas/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "ID_Cobertura,Nombre,Descripcion,PrecioMensual")] Cobertura cobertura)
        {
            if (ModelState.IsValid)
            {
                db.Entry(cobertura).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(cobertura);
        }

        // GET: Coberturas/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Cobertura cobertura = await db.Cobertura.FindAsync(id);
            if (cobertura == null)
            {
                return HttpNotFound();
            }
            return View(cobertura);
        }

        // POST: Coberturas/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            Cobertura cobertura = await db.Cobertura.FindAsync(id);
            db.Cobertura.Remove(cobertura);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

SistemaSeguros/Controllers/PolizasController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using SistemaSeguros;

namespace SistemaSeguros.Controllers
{
    public class PolizasController : Controller
    {
        private SistemaSegurosEntities db = new SistemaSegurosEntities();

        // GET: Polizas
        public async Task<ActionResult> Index()
        {
            var poliza = db.Poliza.Include(p => p.TipoRiesgo);
            return View(await poliza.ToListAsync());
        }

        // GET: Polizas/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Poliza poliza = await db.Poliza.FindAsync(id);
            if (poliza == null)
            {
                return HttpNotFound();
            }
            return View(poliza);
        }

        // GET: Polizas/Create
        public ActionResult Create()
        {
            ViewBag.FK_TipoRiesgo = new SelectList(db.TipoRiesgo, "ID_Riesgo", "Nombre");
            return View();
        }

        // POST: Polizas/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "ID_Poliza,Nombre,Descripcion,FK_TipoRiesgo")] Poliza poliza)
        {
            if (ModelState.IsValid)
            {
                db.Poliza.Add(poliza);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            ViewBag.FK_TipoRiesgo = new SelectList(db.TipoRiesgo, "ID_Riesgo", "Nombre", poliza.FK_TipoRiesgo);
            return View(poliza);
        }

        // GET: Polizas/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Poliza poliza = await db.Poliza.FindAsync(id);
            if (poliza == null)
            {
                return HttpNotFound();
            }
            ViewBag.FK_TipoRiesgo = new SelectList(db.TipoRiesgo, "ID_Riesgo", "Nombre", poliza.FK_TipoRiesgo);
            return View(poliza);
        }

        // POST: Polizas/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "ID_Poliza,Nombre,Descripcion,FK_TipoRiesgo")] Poliza poliza)
        {
            if (ModelState.IsValid)
            {
                db.Entry(poliza).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            ViewBag.FK_TipoRiesgo = new SelectList(db.TipoRiesgo, "ID_Riesgo", "Nombre", poliza.FK_TipoRiesgo);
            return View(poliza);
        }

        // GET: Polizas/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Poliza poliza = await db.Poliza.FindAsync(id);
            if (poliza == null)
            {
                return HttpNotFound();
            }
            return View(poliza);
        }

        // POST: Polizas/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            Poliza poliza = await db.Poliza.FindAsync(id);
            db.Poliza.Remove(poliza);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

SistemaSeguros/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Sistema de Seguros</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/angular")
    @Scripts.Render("~/bundles/SistemaSeguros")
    @RenderSection("scripts", required: false)
    @*<script src="~/Scripts/jquery-3.3.1.js"></script>
        <script src="~/Scripts/bootstrap.min.js"></script>
        <script src="~/Scripts/bootstrap.bundle.min.js"></script>
        <script src="~/Scripts/bootstrap-table.js"></script>*@
    @*<script src="~/Scripts/angular.min.js"></script>
        <script src="~/Scripts/angular-route.min.js"></script>*@

</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark"  style="margin-bottom:2%;">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggler" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="navbar-toggler-icon"></span>
                </button>
                @Html.ActionLink("Inicio", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item active">@Html.ActionLink("Clientes", "Index", "Clientes", null, htmlAttributes: new { @class = "nav-link" })</li>
                    <li class="nav-item active">@Html.ActionLink("Tipos Pólizas", "Index", "Polizas", null, htmlAttributes: new { @class = "nav-link" })</li>
                    @*<li class="nav-item active">@Html.ActionLink("Tipos Coberturas", "Index", "Coberturas", null, htmlAttributes: new { @class = "nav-link" })</li>
                    <li class="nav-item active">@Html.ActionLink("Acerca de", "About", "Home", null, htmlAttributes: new { @class = "nav-link" })</li>*@
                    @*<li class="nav-item active">@Html.ActionLink("Contact", "Contact", "Home", null, htmlAttributes: new { @class = "nav-link" })</li>*@
                    
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content"  ng-app="SistemaSeguros">
        @RenderBody()
     <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Desarrollado por Kenneth Valverde Mora</p>
        </footer>
    </div>


</body>
</html>