SistemaSeguros/Controllers/ClientesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using SistemaSeguros;

namespace SistemaSeguros.Controllers
{
    public class ClientesController : Controller
    {
        private SistemaSegurosEntities db = new SistemaSegurosEntities();

        // GET: Clientes
        public async Task<ActionResult> Index()
        {
            return View(await db.Cliente.ToListAsync());
        }

        // GET: Clientes/Details/5
        public async Task<ActionResult> Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Cliente cliente = await db.Cliente.FindAsync(id);
            if (cliente == null)
            {
                return HttpNotFound();
            }
            return View(cliente);
        }

        // GET: Clientes/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Clientes/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "Identificacion,Nombre,Apellidos,FechaNacimiento,Direccion")] Cliente cliente)
        {
            if (ModelState.IsValid)
            {
                db.Cliente.Add(cliente);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            return View(cliente);
        }

        // GET: Clientes/Edit/5
        public async Task<ActionResult> Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Cliente cliente = await db.Cliente.FindAsync(id);
            if (cliente == null)
            {
                return HttpNotFound();
            }
            return View(cliente);
        }

        // POST: Clientes/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "Identificacion,Nombre,Apellidos,FechaNacimiento,Direccion")] Cliente cliente)
        {
            if (ModelState.IsValid)
            {
                db.Entry(cliente).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(cliente);
        }

        // GET: Clientes/Delete/5
        public async Task<ActionResult> Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Cliente cliente = await db.Cliente.FindAsync(id);
            if (cliente == null)
            {
                return HttpNotFound();
            }
            return View(cliente);
        }

        // POST: Clientes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(string id)
        {
            Cliente cliente = await db.Cliente.FindAsync(id);
            db.Cliente.Remove(cliente);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

SistemaSeguros/Controllers/PolizaPorClientesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using SistemaSeguros;

namespace SistemaSeguros.Controllers
{
    public class PolizaPorClientesController : Controller
    {
        private SistemaSegurosEntities db = new SistemaSegurosEntities();

        // GET: PolizaPorClientes
        public async Task<ActionResult> Index(string idCliente, string nombreCompleto)
        {
            ViewBag.idCliente = idCliente;
            ViewBag.NombreCompleto = nombreCompleto;
            var polizaPorCliente = (!string.IsNullOrEmpty(idCliente)) ? db.PolizaPorCliente.Include(p => p.Cliente).Include(p => p.Poliza).Where(c => c.FK_IDCliente == idCliente) : db.PolizaPorCliente.Include(p => p.Cliente).Include(p => p.Poliza);
            return View(await polizaPorCliente.ToListAsync());
        }

        // GET: PolizaPorClientes/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            PolizaPorCliente polizaPorCliente = await db.PolizaPorCliente.FindAsync(id);
            if (polizaPorCliente == null)
            {
                return HttpNotFound();
            }
            return View(polizaPorCliente);
        }

        // GET: PolizaPorClientes/Create
        public ActionResult Create(string idCliente, string nombreCompleto, string tipo)
        {
            ViewBag.idCliente = idCliente;
            ViewBag.nombreCompleto = nombreCompleto;
            ViewBag.tipo = tipo;
            ViewBag.FK_IDCliente = new SelectList(db.Cliente.Select(x => new { x.Identificacion, Nombre = (x.Identificacion+" - "+x.Nombre+" "+x.Apellidos) }), "Identificacion", "Nombre", idCliente);
            ViewBag.FK_IDEstado = new SelectList(db.EstadoPoliza, "Codigo", "Descripcion");
            ViewBag.FK_IDPoliza = new SelectList(db.Poliza, "ID_Poliza", "Nombre");
            return View();
        }

        // POST: PolizaPorClientes/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(string idCliente, string nombreCompleto)
        {
            return RedirectToAction("Index", new { idCliente = idCliente, nombreCompleto = nombreCompleto });

            //if (ModelState.IsValid)
            //{
            //    db.PolizaPorCliente.Add(polizaPorCliente);
            //    await db.SaveChangesAsync();
                
            //}

            //ViewBag.FK_IDCliente = new SelectList(db.Cliente, "Identificacion", "Nombre", polizaPorCliente.FK_IDCliente);
            //ViewBag.FK_IDEstado = new SelectList(db.EstadoPoliza, "Codigo", "Descripcion", polizaPorCliente.FK_IDEstado);
            //ViewBag.FK_IDPoliza = new SelectList(db.Poliza, "ID_Poliza", "Nombre", polizaPorCliente.FK_IDPoliza);
            //return View(polizaPorCliente);
        }

        // GET: PolizaPorClientes/Edit/5
        public async Task<ActionResult> Edit(int? id, string idCliente, string nombreCompleto, string tipo)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ViewBag.idCliente = idCliente;
            ViewBag.nombreCompleto = nombreCompleto;
            ViewBag.tipo = tipo;
            PolizaPorCliente polizaPorCliente = await db.PolizaPorCliente.FindAsync(id);
            if (polizaPorCliente == null)
            {
                return HttpNotFound();
            }
            ViewBag.FK_IDCliente = new SelectList(db.Cliente.Select(x => new { x.Identificacion, Nombre = (x.Identificacion + " - " + x.Nombre + " " + x.Apellidos) }), "Identificacion", "Nombre",polizaPorCliente.FK_IDCliente);
            ViewBag.FK_IDEstado = new SelectList(db.EstadoPoliza, "Codigo", "Descripcion", polizaPorCliente.FK_IDEstado);
            ViewBag.FK_IDPoliza = new SelectList(db.Poliza, "ID_Poliza", "Nombre", polizaPorCliente.FK_IDPoliza);
            return View(polizaPorCliente);
        }

        // POST: PolizaPorClientes/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "ID_PolizaCliente,FK_IDCliente,FK_IDPoliza,InicioVigenciaPoliza,PrecioPolizaAdquirida,MesesCobertura,FK_IDEstado")] PolizaPorCliente polizaPorCliente)
        {
            if (ModelState.IsValid)
            {
                db.Entry(polizaPorCliente).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            ViewBag.FK_IDCliente = new SelectList(db.Cliente, "Identificacion", "Nombre", polizaPorCliente.FK_IDCliente);
            ViewBag.FK_IDEstado = new SelectList(db.EstadoPoliza, "Codigo", "Descripcion", polizaPorCliente.FK_IDEstado);
            ViewBag.FK_IDPoliza = new SelectList(db.Poliza, "ID_Poliza", "Nombre", polizaPorCliente.FK_IDPoliza);
            return View(polizaPorCliente);
        }

        // GET: PolizaPorClientes/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            PolizaPorCliente polizaPorCliente = await db.PolizaPorCliente.FindAsync(id);
            if (polizaPorCliente == null)
            {
                return HttpNotFound();
            }
            return View(polizaPorCliente);
        }

        // POST: PolizaPorClientes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            PolizaPorCliente polizaPorCliente = await db.PolizaPorCliente.FindAsync(id);
            db.PolizaPorCliente.Remove(polizaPorCliente);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

SistemaSeguros/Views/PolizaPorClientes/Create.cshtml
@model SistemaSeguros.PolizaPorCliente

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

    <h2>Crear Póliza para: @ViewBag.idCliente - @ViewBag.NombreCompleto</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

<div class="form-horizontal" ng-form="DatosForm" ng-controller="SegurosController">
    @*<h4>Datos</h4>*@
    <hr />
    <input type="hidden" id="tipoOp" ng-model="tipoOp" value="@ViewBag.tipo" />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group" ng-show="false">
        @Html.LabelFor(model => model.FK_IDCliente, "Cliente", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <input type="text" id="FK_IDCliente" value="@ViewBag.idCliente" ng-show="false" ng-model="IdClientes" />
            @*@Html.DropDownList("FK_IDCliente", null, "-Seleccione-", htmlAttributes: new { @class = "form-control", ng_required = "true", ng_model = "IdClientes" })*@
            @Html.ValidationMessageFor(model => model.FK_IDCliente, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.FK_IDPoliza, "Tipo Póliza", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <input type="hidden" ng-model="CodigoTipoRiesgo" id="CodigoTipoRiesgo" value="{{CodigoTipoRiesgo}}" />
            @Html.DropDownList("FK_IDPoliza", null, "-Seleccione-", htmlAttributes: new { @class = "form-control", ng_required = "true", ng_model = "PilizaID", ng_change = "getCobPorPoliza()" })
            @Html.ValidationMessageFor(model => model.FK_IDPoliza, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.InicioVigenciaPoliza, "Inicio Vigencia Póliza", htmlAttributes: new { @style = "max-width:50%;", @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.InicioVigenciaPoliza, new { htmlAttributes = new { @class = "form-control", ng_required = "true", type = "date", ng_model = "inicioVigencia", maxlength = "10" } })
            @Html.ValidationMessageFor(model => model.InicioVigenciaPoliza, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.MesesCobertura, "Meses Cobertura", htmlAttributes: new { @style = "max-width:50%;", @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.MesesCobertura, new { htmlAttributes = new { @class = "form-control", ng_required = "true", ng_model = "mesesCobertura", onchange = "sumALL();", maxlength = "3" } })
            @Html.ValidationMessageFor(model => model.MesesCobertura, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        <label class="control-label col-md-2">Coberturas</label>
        <div class="col-md-10">
            @*<select>
                    <option ng-repeat="cobertura in coberturas" value="{{cobertura.ID_Cobertura}}">{{cobertura.Nombre}}</option>
                </select>*@
            <table class="table">
                <thead class="thead-dark">
                    <tr>
                        <th ng-show="false"></th>
                        <th>Nombre</th>
                        <th>Descripción</th>
                        <th>Precio Mensual</th>
                        <th>% Cobertura</th>
                    </tr>
                </thead>
                <tr class="filaTablaSuma" ng-repeat="cobertura in coberturas" id="{{$index}}">
                    <td ng-show="false">{{ cobertura.ID_Cobertura }}</td>
                    <td>{{ cobertura.Nombre }}</td>
                    <td>{{ cobertura.Descripcion }}</td>
                    <td id="PorcentajeSumar">{{ cobertura.PrecioMensual | currency }}</td>
                    <td><input type="text" id="montoSumar" onchange="sumALL();" ng-model="porce" ng-change="coberturas[$index].PorcentajeCobertura=porce" maxlength="3" min="1" max="100"></td>
                </tr>
            </table>

            @*@Html.EditorFor(model => model.PrecioPolizaAdquirida, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PrecioPolizaAdquirida, "", new { @class = "text-danger" })*@
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.PrecioPolizaAdquirida, "Precio Póliza", htmlAttributes: new { @style = "max-width:50%;", @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.PrecioPolizaAdquirida, new { htmlAttributes = new { @class = "form-control", ng_required = "true", @disabled = "true", ng_model = "PrecioTotal" } })
            @Html.ValidationMessageFor(model => model.PrecioPolizaAdquirida, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group" ng-show="false">
        Estado
        <div class="col-md-10">
            @Html.DropDownList("FK_IDEstado", null, htmlAttributes: new { @class = "form-control", @readonly = "true" })
            @Html.ValidationMessageFor(model => model.FK_IDEstado, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input id="flagProcess" ng-model="flagProcess" style="display:none">
            <input id="formCorrect" ng-model="formCorrect" value="{{formCorrect = DatosForm.$invalid}}" style="display:none">
            <input ng-model="botonFinal" onclick="$('#FK_IDCliente').val('@ViewBag.idCliente').change();$('#flagProcess').val('true').change();if (ValidarMontoSeguro() && ($('#formCorrect').val() == 'false')) setTimeout(function () { location.href = '@Url.Action("Index",new { idCliente = ViewBag.idCliente, nombreCompleto = ViewBag.nombreCompleto, tipo = 1 })'; }, 1100); else  { $('#flagProcess').val('false').change(); return false; }" ng-click="crearPolizaCliente()" type="button" value="Crear Póliza" class="btn-dark" />
        </div>
    </div>
    <div class="form-group">
        <input type="text" class="form-control col-md-10" style="width:70%; border:none; background:none; color:red; font-weight:bold" ng-show="DatosForm.$invalid" ng-model="MensajeValidacion" />
    </div>

</div>
}

<div>
    @Html.ActionLink("Volver a lista", "Index", new { idCliente = ViewBag.idCliente, nombreCompleto=ViewBag.nombreCompleto }, null)
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

SistemaSeguros/Views/PolizaPorClientes/Index.cshtml
@model IEnumerable<SistemaSeguros.PolizaPorCliente>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
    <div ng-controller="SegurosController">
        <div ng-show="aparecer" id="listaDiv">
            <h2>Pólizas de: @ViewBag.idCliente - @ViewBag.NombreCompleto</h2>
            <input id="idCliente" class="form-control" ng-show="false" disabled="disabled" value="@ViewBag.idCliente" />
            <input id="nombreCliente" class="form-control" ng-show="false" disabled="disabled" value="@ViewBag.idCliente - @ViewBag.NombreCompleto" />

            <p>
                @Html.ActionLink("Crear Póliza", "Create", new { idCliente = ViewBag.idCliente, nombreCompleto = ViewBag.nombreCompleto, tipo = 1 })
            </p>
            <table class="table">
                <tr>
                    <th>
                        Nombre
                    </th>
                    <th>
                        Fecha Inicio Póliza
                    </th>
                    <th>
                        Meses Cobertura
                    </th>
                    <th>
                        Precio
                    </th>
                    <th>
                        Estado
                    </th>
                    <th></th>
                </tr>

                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.Poliza.Nombre)
                        </td>
                        <td>
                            @Convert.ToDateTime(item.InicioVigenciaPoliza).ToString("dd/MM/yyyy")
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.MesesCobertura)
                        </td>
                        <td>
                            @Convert.ToDouble(item.PrecioPolizaAdquirida).ToString("C2")
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.EstadoPoliza.Descripcion)
                        </td>
                        <td id="idPolizaCliente" ng-show="false">@item.ID_PolizaCliente</td>
                        <td>
                            <input style="border:none;background:none;outline:0px;color:dodgerblue;" onmouseout="this.style.textDecoration=''" onmouseover="this.style.textDecoration='underline'" type="button" ng-model="buttonID" onclick="VerDetalle(this);return false;" ng-click="aparecer=!aparecer;loadDetailsPolizaCliente()" value="Ver Detalle" />
                            @*@Html.ActionLink("Ver Detalles", "Edit", new { id = item.ID_PolizaCliente, idCliente = ViewBag.idCliente, nombreCompleto = ViewBag.nombreCompleto, tipo = 2 })*@
                        </td>
                    </tr>
                }

            </table>
            <div>
                @Html.ActionLink("Volver a Clientes", "Index", "Clientes")
            </div>
        </div>
        <div id="editarDiv" ng-hide="aparecer">
            <h2>Detalles Póliza de Cliente</h2>
            <div class="form-horizontal" id="formEditar" ng-form="DatosForm">
                <hr />
                <input type="hidden" id="tipoOp" ng-model="tipoOp" value="@ViewBag.tipo" />
                <input id="ID_PolizaCliente" ng-hide="true" ng-model="IDPolizaCliente" />
                <div class="form-group">
                    @Html.Label("", "Cliente", htmlAttributes: new { @style = "max-width:70%;", @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        <input id="ClienteID" class="form-control" disabled="disabled" ng-show="false" ng-required="true" ng-model="ClienteID" />
                        <input id="ClienteNombre" class="form-control" disabled="disabled" ng-required="true" ng-model="ClienteNombre" style = "max-width:55%;" />
                    </div>
                </div>
                <div class="form-group">
                    @Html.Label("", "Tipo Póliza", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        <input type="hidden" ng-model="CodigoTipoRiesgo" id="CodigoTipoRiesgo" value="{{CodigoTipoRiesgo}}" />
                        <select id="FK_IDPoliza" class="form-control" ng-required="true" ng-model="PilizaID" ng-change="getCobPorPoliza()">
                            <option value="">-Seleccione-</option>
                            <option ng-repeat="x in tiposPolizas" ng-value="{{x.ID_Poliza}}">{{x.Nombre}}</option>
                        </select>
                    </div>
                </div>

                <div class="form-group">
                    @Html.Label("", "Inicio Vigencia Póliza", htmlAttributes: new { @style = "max-width:50%;", @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        <input id="InicioVigenciaPoliza" type="date" placeholder="dd/MM/yyyy" class="form-control" ng-required="true" ng-model="inicioVigencia" maxlength="10" />
                    </div>
                </div>
                <div class="form-group">
                    @Html.Label("", "Meses Cobertura", htmlAttributes: new { @style = "max-width:50%;", @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        <input id="MesesCobertura" class="form-control" ng-required="true" ng-model="mesesCobertura" onchange="sumALL();" maxlength="3" />
                    </div>
                </div>
                <div class="form-group">
                    <label class="control-label col-md-2">Coberturas</label>
                    <div class="col-md-10">
                        @*<select>
                    <option ng-repeat="cobertura in coberturas" value="{{cobertura.ID_Cobertura}}">{{cobertura.Nombre}}</option>
                </select>*@
                        <table class="table">
                            <thead class="thead-dark">
                                <tr>
                                    <th ng-show="false"></th>
                                    <th>Nombre</th>
                                    <th>Descripción</th>
                                    <th>Precio Mensual</th>
                                    <th>% Cobertura</th>
                                </tr>
                            </thead>
                            <tr class="filaTablaSuma" ng-repeat="cobertura in coberturas" id="{{$index}}">
                                <td ng-show="false">{{ cobertura.ID_Cobertura }}</td>
                                <td>{{ cobertura.Nombre }}</td>
                                <td>{{ cobertura.Descripcion }}</td>
                                <td id="PorcentajeSumar">{{ cobertura.PrecioMensual | currency }}</td>
                                <td><input type="text" value="{{ porce=cobertura.PorcentajeCobertura }}" id="montoSumar" onchange="sumALL();" 
                                           ng-model="porce" ng-change="coberturas[$index].PorcentajeCobertura=porce" maxlength="3" min="1" max="100"></td>
                            </tr>
                        </table>

                        @*@Html.EditorFor(model => model.PrecioPolizaAdquirida, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PrecioPolizaAdquirida, "", new { @class = "text-danger" })*@
                    </div>
                </div>
                <div class="form-group">
                    @Html.Label("", "Precio Póliza", htmlAttributes: new { @style = "max-width:50%;", @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        <input id="PrecioPolizaAdquirida" class="form-control" ng-required="true" disabled="disabled" ng-model="PrecioTotal" />
                    </div>
                </div>



                <div class="form-group">
                    @Html.Label("", "Estado", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        <select ng-model="FK_IDEstado" id="FK_IDEstado" ng-required="true" class="form-control">
                            <option value="">-Seleccione-</option>
                            <option ng-repeat="x in EstadosPolizas" ng-value="{{x.Codigo}}">{{x.Descripcion}}</option>
                        </select>
                    </div>
                </div>

                <div class="form-group">
                    <div class="form-group">
                        <div class="col-md-offset-2 col-md-10">
                            <input id="flagProcess" ng-model="flagProcess" style="display:none">
                            <input id="formCorrect" ng-model="formCorrect" value="{{formCorrect = DatosForm.$invalid}}" style="display:none">
                            <input ng-model="botonFinal" onclick="$('#flagProcess').val('true').change(); if (ValidarMontoSeguro() && ($('#formCorrect').val() == 'false')) setTimeout(function () { location.href = '@Url.Action("Index",new { idCliente = ViewBag.idCliente, nombreCompleto = ViewBag.nombreCompleto, tipo = 1 })'; }, 1000); else { $('#flagProcess').val('false').change(); return false; }" ng-click="editarPolizaCliente();" type="button" value="Editar Póliza" class="btn-dark" />
                            <input ng-model="botonCancelar" onclick="$('#flagProcess').val('false').change(); setTimeout(function () { location.href = '@Url.Action("Index",new { idCliente = ViewBag.idCliente, nombreCompleto = ViewBag.nombreCompleto, tipo = 1 })' }, 300); return false;" type="button" value="Regresar" class="btn-dark" />
                            <input ng-model="botonEliminar" onclick="$('#flagProcess').val('true').change(); if (confirm('Seguro de eliminar póliza?')) setTimeout(function () { location.href = '@Url.Action("Index",new { idCliente=ViewBag.idCliente, nombreCompleto=ViewBag.nombreCompleto, tipo=1 })' }, 700); else { $('#flagProcess').val('false').change(); return false; }" ng-click="DatosForm.$invalid ? alert('Revise formulario, faltan datos') :EliminarPolizaCliente();" type="button" value="Eliminar Póliza" class="btn-dark" />
                        </div>


                    </div>
                    <div class="form-group">
                        <input type="text" class="form-control col-md-10" style="width:70%; border:none; background:none; color:red; font-weight:bold" ng-show="DatosForm.$invalid" ng-model="MensajeValidacion" />
                    </div>
                </div>
        </div>
    </div>
</div>